SHIPMENTS_STATUSES = ('PENDING', 'SHIPPED', 'CANCELLED')
SHIPMENTS_REGEX = '^(' + '|'.join(SHIPMENTS_STATUSES) + ')$'
SHIPMENTS_DESCRIPTION_STATUS = ', '.join(SHIPMENTS_STATUSES)

PRODUCTION_BATCHES_STATUSES = ('INITIALIZED', 'PRODUCTION_STARTED', 'COMPLETED')
PRODUCTION_BATCHES_REGEX = '^(' + '|'.join(PRODUCTION_BATCHES_STATUSES) + ')$'
PRODUCTION_BATCHES_DESCRIPTION_STATUS = ', '.join(PRODUCTION_BATCHES_STATUSES)

PRODUCTS_STATUSES = ('IN_PRODUCTION', 'IN_STOCK', 'OUT_OF_STOCK')
BATCH_DOES_NOT_EXIST = 'One or more batch IDs do not exist'
BATCH_EXISTS_IN_SHIPMENTS = 'One or more batches have already been added in shipments'
PRODUCT_REGEX = '^(' + '|'.join(PRODUCTS_STATUSES) + ')$'
PRODUCT_DESCRIPTION_STATUS = ', '.join(PRODUCTS_STATUSES)


