SHIPMENTS_STATUSES = ('PENDING', 'SHIPPED', 'CANCELLED')
SHIPMENTS_REGEX = '^(' + '|'.join(SHIPMENTS_STATUSES) + ')$'
SHIPMENTS_DESCRIPTION_STATUS = ', '.join(SHIPMENTS_STATUSES)

PRODUCTION_BATCHES_STATUSES = ('INITIALIZED', 'PRODUCTION_STARTED', 'COMPLETED')
PRODUCTION_BATCHES_REGEX = '^(' + '|'.join(PRODUCTION_BATCHES_STATUSES) + ')$'
PRODUCTION_BATCHES_DESCRIPTION_STATUS = ', '.join(PRODUCTION_BATCHES_STATUSES)

PRODUCTS_STATUSES = ('IN_PRODUCTION', 'IN_STOCK', 'OUT_OF_STOCK')
PRODUCT_EXISTS = 'Продукт с таким именем уже существует!'
PRODUCT_REGEX = '^(' + '|'.join(PRODUCTS_STATUSES) + ')$'
PRODUCT_DESCRIPTION_STATUS = ', '.join(PRODUCTS_STATUSES)
